# Week 10 – Foundations of R Software
## Strings & Data Frames — Complete Practical Notebook

**Colab setup:** Change the runtime to **R** before running.  
No setup/install cells are included, as requested.

This notebook implements the runnable examples from the uploaded Week 10 PDF:
- String substitution: `sub()`, `gsub()`
- String searching: `grep()`, `grepl()`
- Case-sensitive and case-insensitive searching
- Combining strings with `c()`
- Data-frame concepts and creation
- `MASS::painters`
- Row names and column names
- Numeric/factor checks
- `summary()`
- Data-frame subsetting
- `attach()` / `detach()`
- `split()`
- `cbind()`, `merge()`, and `rbind()`

## 1. Strings – Substitution and Replacement

The lecture explains that `sub()` replaces the **first** matching occurrence, while `gsub()` performs a **global replacement** and replaces all matching occurrences.

In [1]:
# Lecture example: sub()
y <- "Number of participants: 25"

y
sub("25", "30", y)

[1] "Number of participants: 25"

[1] "Number of participants: 30"

In [2]:
# Another replacement
y <- "Number of participants: 25"

sub("participants", "students", y)

[1] "Number of students: 25"

In [3]:
# Demonstrating that sub() changes only the first occurrence
y <- "Mr. Singh is the smart one. Mr. Singh is funny, too."

y
sub("Mr. Singh", "Professor Jha", y)

[1] "Mr. Singh is the smart one. Mr. Singh is funny, too."

[1] "Professor Jha is the smart one. Mr. Singh is funny, too."

In [4]:
# gsub() replaces ALL occurrences
y <- "Mr. Singh is the smart one. Mr. Singh is funny, too."

gsub("Mr. Singh", "Professor Jha", y)

[1] "Professor Jha is the smart one. Professor Jha is funny, too."

### `sub()` vs `gsub()` — important for exam

| Function | Replacement |
|---|---|
| `sub(old, new, string)` | First occurrence only |
| `gsub(old, new, string)` | All occurrences |

In [5]:
# Side-by-side comparison
sentence <- "R is easy. R is powerful. R is useful."

cat("Original:\n", sentence, "\n\n")
cat("sub():\n", sub("R", "R Programming", sentence), "\n\n")
cat("gsub():\n", gsub("R", "R Programming", sentence), "\n")

Original:
 R is easy. R is powerful. R is useful.

sub():
 R Programming is easy. R is powerful. R is useful.

gsub():
 R Programming is easy. R Programming is powerful. R Programming is useful.

# 2. `grep()` – Searching for Matches

`grep()` searches for a pattern inside each element of a character vector.

By default:
- `value = FALSE` → returns **indices**
- `value = TRUE` → returns the **matching strings**

In [6]:
str <- c(
  "R Course",
  "exercises",
  "include examples of R language"
)

str

[1] "R Course"                       "exercises"
[3] "include examples of R language"

In [7]:
# Lecture example: value = TRUE
grep("ex", str, value = TRUE)

[1] "exercises"                      "include examples of R language"

In [8]:
# Lecture example: value = FALSE
grep("ex", str, value = FALSE)

[1] 2 3

### `grep()` with `ignore.case`

In [9]:
str <- c(
  "R Course",
  "exercises",
  "include examples of r language",
  "in R software."
)

# Case-sensitive search
grep("R", str, ignore.case = FALSE, value = TRUE)

[1] "R Course"       "in R software."

In [10]:
# Case-insensitive search
grep("R", str, ignore.case = TRUE, value = TRUE)

[1] "R Course"                       "exercises"
[3] "include examples of r language" "in R software."

In [11]:
# Case-sensitive search returning indices
grep("R", str, ignore.case = FALSE, value = FALSE)

[1] 1 4

In [12]:
# Case-insensitive search returning indices
grep("R", str, ignore.case = TRUE, value = FALSE)

[1] 1 2 3 4

### Important exam point

`ignore.case = FALSE` means uppercase/lowercase matter.

`ignore.case = TRUE` means uppercase/lowercase are ignored while matching.

## 3. `grep()` with Combined Strings

In [13]:
x <- "R course 24.07.2021"
y <- "Number of participants: 25"

# Combine the two strings
combined <- c(x, y)
combined

[1] "R course 24.07.2021"        "Number of participants: 25"

In [14]:
# Search for "our"
grep("our", c(x, y))

[1] 1

`"our"` occurs in `"course"`, which is the **first element**, so the result is `1`.

In [15]:
# Search for "Num"
grep("Num", c(x, y))

[1] 2

`"Num"` occurs in `"Number"` in the **second element**, so the result is `2`.

## 4. `grepl()` – TRUE/FALSE Matching

Unlike `grep()`, `grepl()` returns a logical vector:

- `TRUE` → pattern is present
- `FALSE` → pattern is absent

In [16]:
str <- c(
  "R Course",
  "exercises",
  "include examples of R language"
)

grepl("R", str)

[1]  TRUE FALSE  TRUE

In [17]:
grepl("ex", str)

[1] FALSE  TRUE  TRUE

### `grepl()` with case sensitivity

In [18]:
str <- c(
  "R Course",
  "exercises",
  "include examples of r language",
  "in R software."
)

# Case-sensitive
grepl("R", str, ignore.case = FALSE)

[1]  TRUE FALSE FALSE  TRUE

In [19]:
# Case-insensitive
grepl("R", str, ignore.case = TRUE)

[1] TRUE TRUE TRUE TRUE

## 5. Quick String Practice

Run these to reinforce the four major string functions.

In [20]:
texts <- c(
  "R programming is useful",
  "Python programming is also useful",
  "R is used for statistics",
  "Data analysis is important"
)

# Find elements containing "R"
grep("R", texts, value = TRUE)

# Find their indices
grep("R", texts)

# TRUE/FALSE for each element
grepl("R", texts)

# Replace only first matching "programming"
sub("programming", "coding", texts)

# Replace every matching "programming"
gsub("programming", "coding", texts)

[1] "R programming is useful"  "R is used for statistics"

[1] 1 3

[1]  TRUE FALSE  TRUE FALSE

[1] "R coding is useful"           "Python coding is also useful"
[3] "R is used for statistics"     "Data analysis is important"

[1] "R coding is useful"           "Python coding is also useful"
[3] "R is used for statistics"     "Data analysis is important"

# 6. Data Frames

The lecture defines a data frame as a structure in which variables of equal length are combined, with each row representing observations on the same unit.

Unlike a matrix, a data frame can contain different types such as:
- numeric variables
- character strings
- factors

In [21]:
# Create a simple data frame
student_df <- data.frame(
  Name = c("Asha", "Riya", "Neha", "Pooja"),
  Marks = c(85, 72, 91, 68),
  Branch = c("CMPN", "IT", "CMPN", "EXTC")
)

student_df

  Name  Marks Branch
1 Asha  85    CMPN
2 Riya  72    IT
3 Neha  91    CMPN
4 Pooja 68    EXTC

In [22]:
# Inspect the data frame
class(student_df)
dim(student_df)
names(student_df)
colnames(student_df)
str(student_df)

[1] "data.frame"

[1] 4 3

[1] "Name"   "Marks"  "Branch"

[1] "Name"   "Marks"  "Branch"

'data.frame':	4 obs. of  3 variables:
 $ Name  : chr  "Asha" "Riya" "Neha" "Pooja"
 $ Marks : num  85 72 91 68
 $ Branch: chr  "CMPN" "IT" "CMPN" "EXTC"

### Accessing variables/columns

In [23]:
student_df$Name
student_df$Marks
student_df$Branch

[1] "Asha"  "Riya"  "Neha"  "Pooja"

[1] 85 72 91 68

[1] "CMPN" "IT"   "CMPN" "EXTC"

## 7. `MASS::painters` Data Frame

The Week 10 lecture uses the `painters` data frame from the MASS package. It contains four numerical variables — Composition, Drawing, Colour and Expression — and the factor variable School.

In [24]:
# MASS is normally available in an R runtime
library(MASS)

painters <- MASS::painters

painters

                Composition Drawing Colour Expression School
Da Udine        10           8      16      3         A
Da Vinci        15          16       4     14         A
Del Piombo       8          13      16      7         A
Del Sarto       12          16       9      8         A
Fr. Penni        0          15       8      0         A
Guilio Romano   15          16       4     14         A
Michelangelo     8          17       4      8         A
Perino del Vaga 15          16       7      6         A
Perugino         4          12      10      4         A
Raphael         17          18      12     18         A
F. Zucarro      10          13       8      8         B
Fr. Salviata    13          15       8      8         B
Parmigiano      10          15       6      6         B
Primaticcio     15          14       7     10         B
T. Zucarro      13          14      10      9         B
Volterra        12          15       5      8         B
Barocci         14          15       6     10         C
Cortona         16          14      12      6         C
Josepin         10          10       6      2         C
L. Jordaens     13          12       9      6         C
Testa           11          15       0      6         C
Vanius          15          15      12     13         C
Bassano          6           8      17      0         D
Bellini          4           6      14      0         D
Giorgione        8           9      18      4         D
Murillo          6           8      15      4         D
Palma Giovane   12           9      14      6         D
Palma Vecchio    5           6      16      0         D
Pordenone        8          14      17      5         D
Tintoretto      15          14      16      4         D
Titian          12          15      18      6         D
Veronese        15          10      16      3         D
Albani          14          14      10      6         E
Caravaggio       6           6      16      0         E
Corregio        13          13      15     12         E
Domenichino     15          17       9     17         E
Guercino        18          10      10      4         E
Lanfranco       14          13      10      5         E
The Carraci     15          17      13     13         E
Durer            8          10      10      8         F
Holbein          9          10      16     13         F
Pourbus          4          15       6      6         F
Van Leyden       8           6       6      4         F
Diepenbeck      11          10      14      6         G
J. Jordaens     10           8      16      6         G
Otho Venius     13          14      10     10         G
Rembrandt       15           6      17     12         G
Rubens          18          13      17     17         G
Teniers         15          12      13      6         G
Van Dyck        15          10      17     13         G
Bourdon         10           8       8      4         H
Le Brun         16          16       8     16         H
Le Suer         15          15       4     15         H
Poussin         15          17       6     15         H

In [25]:
# Row names
rownames(painters)

 [1] "Da Udine"        "Da Vinci"        "Del Piombo"      "Del Sarto"
 [5] "Fr. Penni"       "Guilio Romano"   "Michelangelo"    "Perino del Vaga"
 [9] "Perugino"        "Raphael"         "F. Zucarro"      "Fr. Salviata"
[13] "Parmigiano"      "Primaticcio"     "T. Zucarro"      "Volterra"
[17] "Barocci"         "Cortona"         "Josepin"         "L. Jordaens"
[21] "Testa"           "Vanius"          "Bassano"         "Bellini"
[25] "Giorgione"       "Murillo"         "Palma Giovane"   "Palma Vecchio"
[29] "Pordenone"       "Tintoretto"      "Titian"          "Veronese"
[33] "Albani"          "Caravaggio"      "Corregio"        "Domenichino"
[37] "Guercino"        "Lanfranco"       "The Carraci"     "Durer"
[41] "Holbein"         "Pourbus"         "Van Leyden"      "Diepenbeck"
[45] "J. Jordaens"     "Otho Venius"     "Rembrandt"       "Rubens"
[49] "Teniers"         "Van Dyck"        "Bourdon"         "Le Brun"
[53] "Le Suer"         "Poussin"

In [26]:
# Column names
colnames(painters)

[1] "Composition" "Drawing"     "Colour"      "Expression"  "School"

### Check whether variables are numeric

In [27]:
is.numeric(painters$School)
is.numeric(painters$Drawing)

[1] FALSE

[1] TRUE

### Check whether variables are factors

In [28]:
is.factor(painters$School)
is.factor(painters$Drawing)

[1] TRUE

[1] FALSE

Expected idea:

- `School` → factor
- `Drawing` → numeric

This is one of the explicit checks shown in the lecture.

## 8. `summary()` on a Data Frame

In [29]:
summary(painters)

  Composition       Drawing          Colour        Expression         School
 Min.   : 0.00   Min.   : 6.00   Min.   : 0.00   Min.   : 0.000   A      :10
 1st Qu.: 8.25   1st Qu.:10.00   1st Qu.: 7.25   1st Qu.: 4.000   D      :10
 Median :12.50   Median :13.50   Median :10.00   Median : 6.000   E      : 7
 Mean   :11.56   Mean   :12.46   Mean   :10.94   Mean   : 7.667   G      : 7
 3rd Qu.:15.00   3rd Qu.:15.00   3rd Qu.:16.00   3rd Qu.:11.500   B      : 6
 Max.   :18.00   Max.   :18.00   Max.   :18.00   Max.   :18.000   C      : 6
                                                                  (Other): 8

For numerical variables, `summary()` displays:

- Minimum
- 1st Quartile
- Median
- Mean
- 3rd Quartile
- Maximum

For the categorical `School` variable, it displays frequencies.

The lecture notes that only the most frequent categories are displayed by default, with less frequent categories combined as `Other`.

In [30]:
# Summary of a single categorical variable
summary(painters$School)

 A  B  C  D  E  F  G  H
10  6  6 10  7  4  7  4

In [31]:
# Summary of a single numeric variable
summary(painters$Composition)

   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.
   0.00    8.25   12.50   11.56   15.00   18.00

## 9. `attach()` and `detach()`

In [32]:
# Attach the data frame
attach(painters)

# Now columns can be referred to directly
summary(School)
summary(Composition)

# Always detach when finished
detach(painters)

 A  B  C  D  E  F  G  H
10  6  6 10  7  4  7  4

   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.
   0.00    8.25   12.50   11.56   15.00   18.00

After `detach(painters)`, the variables are no longer available as standalone names. The normal form is again:

```r
painters$School
painters$Composition
```

In [33]:
# Safe/default form after detach
summary(painters$School)
summary(painters$Composition)

 A  B  C  D  E  F  G  H
10  6  6 10  7  4  7  4

   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.
   0.00    8.25   12.50   11.56   15.00   18.00

## 10. Subsetting a Data Frame

In [34]:
# Select painters belonging to School F
subset(painters, School == "F")

           Composition Drawing Colour Expression School
Durer      8           10      10      8         F
Holbein    9           10      16     13         F
Pourbus    4           15       6      6         F
Van Leyden 8            6       6      4         F

In [35]:
# Equivalent logical-indexing approach
painters[painters[["School"]] == "F", ]

           Composition Drawing Colour Expression School
Durer      8           10      10      8         F
Holbein    9           10      16     13         F
Pourbus    4           15       6      6         F
Van Leyden 8            6       6      4         F

In [36]:
# Select painters with Composition <= 6
subset(painters, Composition <= 6)

              Composition Drawing Colour Expression School
Fr. Penni     0           15       8     0          A
Perugino      4           12      10     4          A
Bassano       6            8      17     0          D
Bellini       4            6      14     0          D
Murillo       6            8      15     4          D
Palma Vecchio 5            6      16     0          D
Caravaggio    6            6      16     0          E
Pourbus       4           15       6     6          F

### Remove unwanted columns with `select=`

In [37]:
# Remove column 3 (Colour) and column 5 (School)
subset(
  painters,
  School == "F",
  select = c(-3, -5)
)

           Composition Drawing Expression
Durer      8           10       8
Holbein    9           10      13
Pourbus    4           15       6
Van Leyden 8            6       4

In [38]:
# Instead of removing columns, explicitly select the required ones
subset(
  painters,
  School == "F",
  select = c(Composition, Drawing, Expression)
)

           Composition Drawing Expression
Durer      8           10       8
Holbein    9           10      13
Pourbus    4           15       6
Van Leyden 8            6       4

## 11. `split()` – Partition a Data Frame

The lecture uses `split()` to partition `painters` according to the factor variable `School`.

In [39]:
splitted <- split(painters, painters$School)

splitted

$A
                Composition Drawing Colour Expression School
Da Udine                 10       8     16          3      A
Da Vinci                 15      16      4         14      A
Del Piombo                8      13     16          7      A
Del Sarto                12      16      9          8      A
Fr. Penni                 0      15      8          0      A
Guilio Romano            15      16      4         14      A
Michelangelo              8      17      4          8      A
Perino del Vaga          15      16      7          6      A
Perugino                  4      12     10          4      A
Raphael                  17      18     12         18      A

$B
             Composition Drawing Colour Expression School
F. Zucarro            10      13      8          8      B
Fr. Salviata          13      15      8          8      B
Parmigiano            10      15      6          6      B
Primaticcio           15      14      7         10      B
T. Zucarro            13      14     10          9      B
Volterra              12      15      5          8      B

$C
            Composition Drawing Colour Expression School
Barocci              14      15      6         10      C
Cortona              16      14     12          6      C
Josepin              10      10      6          2      C
L. Jordaens          13      12      9          6      C
Testa                11      15      0          6      C
Vanius               15      15     12         13      C

$D
              Composition Drawing Colour Expression School
Bassano                 6       8     17          0      D
Bellini                 4       6     14          0      D
Giorgione               8       9     18          4      D
Murillo                 6       8     15          4      D
Palma Giovane          12       9     14          6      D
Palma Vecchio           5       6     16          0      D
Pordenone               8      14     17          5      D
Tintoretto             15      14     16          4      D
Titian                 12      15     18          6      D
Veronese               15      10     16          3      D

$E
            Composition Drawing Colour Expression School
Albani               14      14     10          6      E
Caravaggio            6       6     16          0      E
Corregio             13      13     15         12      E
Domenichino          15      17      9         17      E
Guercino             18      10     10          4      E
Lanfranco            14      13     10          5      E
The Carraci          15      17     13         13      E

$F
           Composition Drawing Colour Expression School
Durer                8      10     10          8      F
Holbein              9      10     16         13      F
Pourbus              4      15      6          6      F
Van Leyden           8       6      6          4      F

$G
            Composition Drawing Colour Expression School
Diepenbeck           11      10     14          6      G
J. Jordaens          10       8     16          6      G
Otho Venius          13      14     10         10      G
Rembrandt            15       6     17         12      G
Rubens               18      13     17         17      G
Teniers              15      12     13          6      G
Van Dyck             15      10     17         13      G

$H
        Composition Drawing Colour Expression School
Bourdon          10       8      8          4      H
Le Brun          16      16      8         16      H
Le Suer          15      15      4         15      H
Poussin          15      17      6         15      H

In [40]:
# Names of the resulting groups
names(splitted)

[1] "A" "B" "C" "D" "E" "F" "G" "H"

In [41]:
# Individual groups
splitted$A
splitted$F
splitted$H

                Composition Drawing Colour Expression School
Da Udine        10           8      16      3         A
Da Vinci        15          16       4     14         A
Del Piombo       8          13      16      7         A
Del Sarto       12          16       9      8         A
Fr. Penni        0          15       8      0         A
Guilio Romano   15          16       4     14         A
Michelangelo     8          17       4      8         A
Perino del Vaga 15          16       7      6         A
Perugino         4          12      10      4         A
Raphael         17          18      12     18         A

           Composition Drawing Colour Expression School
Durer      8           10      10      8         F
Holbein    9           10      16     13         F
Pourbus    4           15       6      6         F
Van Leyden 8            6       6      4         F

        Composition Drawing Colour Expression School
Bourdon 10           8      8       4         H
Le Brun 16          16      8      16         H
Le Suer 15          15      4      15         H
Poussin 15          17      6      15         H

In [42]:
# Each split object is itself a data frame
is.data.frame(splitted$A)
is.data.frame(splitted$F)

[1] TRUE

[1] TRUE

# 12. Combining Data Frames

The lecture gives three main techniques:

- `cbind()` → combine columns side-by-side
- `merge()` → join using a common column
- `rbind()` → stack rows vertically

## 13. `cbind()` – Combine Side-by-Side

In [43]:
df1 <- data.frame(
  state = c("UP", "MP", "AP", "JK"),
  popnsize = c(1000, 2000, 3000, 4000)
)

df2 <- data.frame(
  state = c("UP", "MP", "AP", "JK"),
  samplesize = c(100, 200, 300, 400),
  surveycompleted = c("Yes", "No", "Yes", "No")
)

df1
df2

  state popnsize
1 UP    1000
2 MP    2000
3 AP    3000
4 JK    4000

  state samplesize surveycompleted
1 UP    100        Yes
2 MP    200        No
3 AP    300        Yes
4 JK    400        No

In [44]:
# Horizontally combine the two data frames
cbind(df1, df2)

  state popnsize state samplesize surveycompleted
1 UP    1000     UP    100        Yes
2 MP    2000     MP    200        No
3 AP    3000     AP    300        Yes
4 JK    4000     JK    400        No

### Important

`cbind()` combines columns **by position/row**.

It does not use `state` to match rows.

## 14. `merge()` – Join Using a Common Column

In [45]:
# Merge using the common variable 'state'
merged_df <- merge(df1, df2, by = "state")

merged_df

  state popnsize samplesize surveycompleted
1 AP    3000     300        Yes
2 JK    4000     400        No
3 MP    2000     200        No
4 UP    1000     100        Yes

Here `state` is common to both data frames, so `merge()` matches records using `state`.

The lecture's example uses:

```r
merge(df1, df2, by = "state")
```

In [46]:
# Explicitly inspect the result
str(merged_df)

'data.frame':	4 obs. of  4 variables:
 $ state          : chr  "AP" "JK" "MP" "UP"
 $ popnsize       : num  3000 4000 2000 1000
 $ samplesize     : num  300 400 200 100
 $ surveycompleted: chr  "Yes" "No" "No" "Yes"

### `merge()` with `by.x` and `by.y`

In [47]:
# Demonstration where the common column has different names
left_df <- data.frame(
  state_code = c("UP", "MP", "AP", "JK"),
  population = c(1000, 2000, 3000, 4000)
)

right_df <- data.frame(
  state = c("AP", "JK", "MP", "UP"),
  capital = c("Amaravati", "Srinagar", "Bhopal", "Lucknow")
)

merge(
  left_df,
  right_df,
  by.x = "state_code",
  by.y = "state"
)

  state_code population capital
1 AP         3000       Amaravati
2 JK         4000       Srinagar
3 MP         2000       Bhopal
4 UP         1000       Lucknow

## 15. `rbind()` – Combine Vertically

In [48]:
df11 <- data.frame(
  state = c("UP", "MP", "AP", "JK"),
  popnsize = c(1000, 2000, 3000, 4000)
)

df22 <- data.frame(
  state = c("Bihar", "Delhi", "Punjab"),
  popnsize = c(100, 200, 300)
)

df11
df22

  state popnsize
1 UP    1000
2 MP    2000
3 AP    3000
4 JK    4000

  state  popnsize
1 Bihar  100
2 Delhi  200
3 Punjab 300

In [49]:
# Stack the second data frame below the first
rbind(df11, df22)

  state  popnsize
1 UP     1000
2 MP     2000
3 AP     3000
4 JK     4000
5 Bihar   100
6 Delhi   200
7 Punjab  300

### Important condition for `rbind()`

The data frames should have compatible columns. Here both have:

- `state`
- `popnsize`

so the rows can be stacked.

# 16. Combined Exam-Practice Cell

This cell puts the most important Week 10 operations together.

In [50]:
# STRING OPERATIONS
s <- c("R course", "R programming", "Python course", "Data analysis")

grep("R", s)
grep("course", s, value = TRUE)
grepl("R", s)
sub("course", "class", s)
gsub("R", "R Programming", s)

# DATA FRAME
d <- data.frame(
  state = c("UP", "MP", "AP"),
  population = c(1000, 2000, 3000),
  region = c("North", "Central", "South")
)

d
summary(d)

# SUBSETTING
subset(d, population > 1500)

# SPLIT
split(d, d$region)

# COMBINE
extra <- data.frame(
  state = c("JK", "BR"),
  population = c(4000, 500),
  region = c("North", "East")
)

rbind(d, extra)

# COLUMNS
cbind(d, code = c(1, 2, 3))

[1] 1 2

[1] "R course"      "Python course"

[1]  TRUE  TRUE FALSE FALSE

[1] "R class"       "R programming" "Python class"  "Data analysis"

[1] "R Programming course"      "R Programming programming"
[3] "Python course"             "Data analysis"

  state population region
1 UP    1000       North
2 MP    2000       Central
3 AP    3000       South

       state     population         region
 Length   :3   Min.   :1000   Length   :3
 N.unique :3   1st Qu.:1500   N.unique :3
 N.blank  :0   Median :2000   N.blank  :0
 Min.nchar:2   Mean   :2000   Min.nchar:5
 Max.nchar:2   3rd Qu.:2500   Max.nchar:7
               Max.   :3000

  state population region
2 MP    2000       Central
3 AP    3000       South

$Central
  state population  region
2    MP       2000 Central

$North
  state population region
1    UP       1000  North

$South
  state population region
3    AP       3000  South

  state population region
1 UP    1000       North
2 MP    2000       Central
3 AP    3000       South
4 JK    4000       North
5 BR     500       East

  state population region  code
1 UP    1000       North   1
2 MP    2000       Central 2
3 AP    3000       South   3